name: balda2
description: A new Flutter project.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  device_preview: ^1.1.0
  dio: ^4.0.6
  dotted_border: ^2.0.0+2
  easy_localization: ^3.0.1
  flutter_lints: ^2.0.1
  flutter_screenutil: ^5.5.3+2
  flutter_staggered_grid_view: ^0.6.1
  flutter_svg: ^1.1.0
  google_fonts: ^3.0.1
  http: ^0.13.4
  jwt_decoder: ^2.0.1
  modal_bottom_sheet: ^2.0.1
  url_launcher: ^6.1.2
  cached_network_image: ^3.2.1
  shared_preferences: ^2.0.15


flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/